site_name: MiniBabelLibrary
site_url: https://ruoxining.github.io/OBvault
repo_url: https://github.com/ruoxining/OBvault
repo_name: OBvault

nav:
  - 'index.md'
  - 申请心得: 
    - 索引: 'Application/index.md'
    - 24fall申请记录: 'Application/【TODO】我的24fall申请记录.md' 
    - 英专转CS&NLP指北: 'Application/ZJU English Major to CS&NLP.md'
    - 搬运NLP申请PhD经验: 'Application/NLP Global PHD Equality Digest.md'
  - CS专栏: 
    - 索引: 'CS_Notes/index.md'
    - C++持续进步: 
      - ZJU听课: 'CS_Notes/我的C++学习记录/听课（ZJU & Stanford CS106B）.md'
      - ZJU期末复习: 'CS_Notes/我的C++学习记录/ZJU 期末复习.md'
      - 继承: 'CS_Notes/我的C++学习记录/继承 Inheritance.md'
      - 模板和标准模板库: 'CS_Notes/我的C++学习记录/模板和标准模板库 Template & STL.md'
      - 类型和类型转换: 'CS_Notes/我的C++学习记录/类型和类型转换Type & Type Conversion.md'
      - 文件读写: 'CS_Notes/我的C++学习记录/文件读写 File IO.md'
      - 浅拷贝和深拷贝: 'CS_Notes/我的C++学习记录/浅拷贝和深拷贝 Shallow copy & Deep copy.md'
      - 命名空间: 'CS_Notes/我的C++学习记录/命名空间 Namespace.md'
    - OS操作系统: 
      - Index: 'CS_Notes/OS操作系统/index.md'
      - 引入: 'CS_Notes/OS操作系统/Lecture_Overview.md'
      - 进程与同步: 'CS_Notes/OS操作系统/进程与同步.md'
      - 内存/存储/文件系统: 'CS_Notes/OS操作系统/内存_存储_文件系统.md'
    - 8086&80386汇编: 'CS_Notes/8086&80386汇编.md'
    - 编程规范文档模板: 'CS_Notes/编程规范文档模板.md'
    - C语言: 'CS_Notes/C语言.md'
    - C大程libgraphics踩坑文档: 'CS_Notes/C大程libgraphics踩坑文档.md'
    - 爬虫: 'CS_Notes/Crawler🕷.md'
  - DL专栏: 
    - 索引: 'DL_Notes/index.md'
    - NLP Theory: 
      - CoT prompt: 'DL_Notes/NLP/Chain-of-Thought.md'
      - Contrastive Learning and Interpretability: 'DL_Notes/NLP_Theory/Contrastive Learning and Interpretability.md'
    - NLP Tech:
      - 规则提取文本格式经验总结: DL_Notes/NLP_Tech/规则提取文本格式经验总结.md
    - Python用法速查:
      - IPDB: 'DL_Notes/Python_Usage/IPDB.md'
      - Pandas DF速查: 'DL_Notes/Python_Usage/Pandas Dataframe常用.md'
      - Python类速查: 'DL_Notes/Python_Usage/Python的面向对象使用技巧.md'
      - Pytorch速查: 'DL_Notes/Python_Usage/Pytorch 常用命令.md'
    - 命令行用法速查: 
      - Anaconda速查: 'DL_Notes/Terminal_Usage/Anaconda常用命令.md'
      - Linux命令行速查: 'DL_Notes/Terminal_Usage/Linux.md'
      - tmux速查: 'docs/DL_Notes/Terminal_Usage/tmux.md'
  - Linguistics专栏:
    - Index: 'Linguistics/index.md'
    - Phonetics:
      - Reduction in verb.+prep.: 'Linguistics_Notes/Phonetics/Reduction of Intentional verb+prep.md'
      - Signal Basics: 'Linguistics_Notes/Phonetics/Signal Basics.md'
    - Syntax: 
      - 转换生成句法: 'Linguistics/转换生成句法.md'
      - 乔姆斯基普遍语法: 'Linguistics_Notes/Syntax/Chomsky’s Universal Grammar.md'
      - UD和SUD: 'docs/Linguistics_Notes/Syntax/UD and SUD.md'
    - Semantics: 
      - Index: 'Linguistics_Notes/Semantics/index.md'
      - Definition Clearification: 'Linguistics_Notes/Semantics/Definition Clearification.md'
      - Logics & Formal Semantics: 'Linguistics_Notes/Semantics/Logics & Formal Semantics.md'
      - Ambiguity: 'Linguistics_Notes/Semantics/Ambiguity.md'
    - Pragmatics: 'index.md'
  - Math专栏: 
    - 索引: 'Math_Notes/index.md'
    - 图论: 'Math_Notes/Graph Theory/Laplacian Matrix.md'
    - 零散的题: 'Math_Notes/零散的题.md'
  - 其它课程:
    - 索引: 'Other_Courses/index.md' 
    - 钢琴期末复习: 'Other_Courses/打开艺术之门-钢琴期末复习.md'
  - 瞎说一些东西: 
    - 索引: '瞎说一些东西/index.md'
    - 好用的工具: '瞎说一些东西/好用的工具.md'
    - Notion vs. Obsidian: '瞎说一些东西/Notion和Obsidian，选哪一个.md'
    - ZOTERO简介: '瞎说一些东西/ZOTERO 简介及配置教程.md'



theme:
  name: material
  language: zh
  palette:
    primary: black
    accent: indigo
  feature:
    tabs: true
